# -*- coding: utf-8 -*-
"""Algorithmic trading

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SPAA3B2Td7sT28MTQmAnXzzXHnfL0Ciy
"""

import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

from google.colab import files
uploaded = files .upload()

AAPL = pd.read_csv('AAPL.csv')
#show the data
AAPL

plt.figure(figsize=(12.5,4.5))
plt.plot(AAPL['Adj Close'], label = 'AAPL')
plt.title('Apple Adj. Close History')
plt.xlabel('Oct. 02, 2006 - Dec. 30, 2011')
plt.ylabel('Adj. Close  USD ($)')
plt.legend(loc='upper left')
plt.show()

SMA30 = pd.DataFrame()
SMA30['ADJ close price'] = AAPL['Adj Close'].rolling(window=30).mean()
SMA30

SMA100 = pd.DataFrame()
SMA100['adjclose price'] = AAPL['Adj Close'].rolling (window=100).mean()
SMA100

plt.figure(figsize=(12.5,4.5))
plt.plot(AAPL['Adj Close'], label = 'AAPL')
plt.plot(SMA30['ADJ close price'] , label = 'SMA30')
plt.plot(SMA100['adjclose price'] , label = 'SMA100')
plt.title('apple Adj.close History')
plt.xlabel('Oct.02,2006 - Dec.30,2011')
plt.ylabel('Adj close USD($)')
plt.legend(loc= 'upper left')
plt.show()

data =pd.DataFrame()
data['AAPL'] = AAPL['Adj Close']
data['SMA30'] = SMA30['ADJ close price']
data['SMA100'] =SMA100['adjclose price']
data

def buy_sell(data):
  sigPriceBuy=[]
  sigPriceSell=[]
  flag=-1
  for i in range(0,len(data)):
    if data['SMA30'][i]>data['SMA100'][i]:
      if flag!=1:
        sigPriceBuy.append(data['AAPL'][i])
        sigPriceSell.append(np.nan)
        flag=1
      else:
        sigPriceBuy.append(np.nan)
        sigPriceSell.append(np.nan)
    elif data['SMA30'][i]<data['SMA100'][i]:
      if flag!=0:
        sigPriceBuy.append(np.nan)
        sigPriceSell.append(data['AAPL'][i])
      else:
        sigPriceBuy.append(np.nan)
        sigPriceSell.append(np.nan)
    else:
      sigPriceBuy.append(np.nan)
      sigPriceSell.append(np.nan)
  return(sigPriceBuy,sigPriceSell)

#store the buy and sell data into a variable
buy_sell = buy_sell(data)
data['Signal_price_buy']=buy_sell[0]
data['signal_price_sell']=buy_sell[1]

data

plt.figure(figsize=(12.6,4.6))
plt.plot(data['AAPL'] , label = 'AAPL' , alpha = 0.35)
plt.plot(data['SMA30'] , label = 'SMA30' ,alpha = 0.35)
plt.plot(data['SMA100'], label = 'SMA100', alpha = 0.35)
plt.scatter(data.index,data['Signal_price_buy'], label = 'Buy' , marker = '^' , color = 'green')
plt.scatter(data.index, data['signal_price_sell'], label = 'Sell' , marker = 'v' , color = 'red')
plt.title('Apple Adj. close price history buy & sell signals ')
plt.xlabel('oct.02,2006 - dec. 30 , 2011')
plt.ylabel('Adj.close Price Usd($)')
plt.legend(loc= 'upper left')
plt.show()

